### ISSUE TITLE
Inefficient Mean()?

### ISSUE THREAD

**Issue by brucala** [joshday/OnlineStatsBase.jl#19]
First of all, thanks for the fantastic OnlineStats package!

I've noticed that `Mean()` is quite slow when compared to (e.g.) `Variance()`, which I would expect to be slower. Some timing examples below (only giving time from second runs):
```julia
julia> @time reduce(Mean(), table, select=:C14)
  4.406728 seconds (40.45 M allocations: 618.137 MiB, 1.26% gc time)
Mean: n=40428967 | value=18841.8

julia> @time reduce(Variance(), table, select=:C14)
  0.152765 seconds (24.03 k allocations: 1.174 MiB)
Variance: n=40428967 | value=2.45962e7
```
A more than 10x difference is observed in favor of `Variance()`. Note: I chose to give the examples based on JuliaDB instead of purely OnlineStats because the times are more striking, but the effect is also noticeable with pure OnlineStats calls.

Inspecting the code for the fit function of `Mean()`:
https://github.com/joshday/OnlineStatsBase.jl/blob/1737743cf6f88cf8644435a5a2a5efacf558f9c0/src/stats.jl#L343
I believe the inefficiency comes from the condition in the ternary operator, which I believe is unnecessary. Indeed if I modify the code to:
```
    o.μ = smooth(o.μ, x, T(o.weight(o.n += 1)))
```
I obtain the following timing measurements:
```
julia> @time reduce(Mean(), table, select=:C14)
  0.135243 seconds (24.03 k allocations: 1.174 MiB)
Mean: n=40428967 | value=18841.8
```

Does this make sense? Can it be fixed?

I don't know if the right approach here is for me to open a pull request. Please, let me know if that's the case.

**Comment by joshday** [comment]
> First of all, thanks for the fantastic OnlineStats package!

Thanks!

---

It took me a while to remember why I used the ternary operator...

`ExponentialWeight` is "problematic" since the weight is constant, but `OnlineStat`s generally assume the first weight value is 1.  Since a `Mean`'s value is initialized at 0, it implicitly has a "0-th" value of 0.  The ternary operator is there to avoid this:

```
o = Mean(weight = n -> .1)

fit!(o, 10)

value(o) == 1
```

Previously I made an `ExponentialWeight`'s first value always 1, but this caused weirdness elsewhere.  A few months ago I changed it.

I don't do this special-casing of the first weight not being 1 anywhere else, so I've used your suggestion here.  The release was just merged.
